import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { GlobalContextProvider, useGlobalContext } from '@/utils/globalContext'
import Result from '@/components/result/result'
import Nav from '@/components/nav/nav'

const font = Roboto({ subsets: ['latin'], weight: ['300', '400', '700'] })

export default function Home() {

  const { searchResults } = useGlobalContext();

  console.log(searchResults, "context");

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="https://http2.mlstatic.com/ui/webfonts/v3.0.0/proxima-nova/proximanova-light.woff2" as="font" type="font/woff2" crossOrigin="anonymous" data-head-react="true" />
        <link rel="preload" href="https://http2.mlstatic.com/ui/webfonts/v3.0.0/proxima-nova/proximanova-regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" data-head-react="true" />
        <link rel="preload" href="https://http2.mlstatic.com/ui/webfonts/v3.0.0/proxima-nova/proximanova-semibold.woff2" as="font" type="font/woff2" crossOrigin="anonymous" data-head-react="true" />
      </Head>
      <GlobalContextProvider>
        <main className={styles.main}>
          <Nav />
          <Result />
        </main>
      </GlobalContextProvider>
    </>
  )
}
